export interface Currency {
  code: string;
  symbol: string;
  name: string;
  region: 'Major' | 'Middle East' | 'Africa' | 'Asia' | 'Europe' | 'North America' | 'South America' | 'Oceania';
}

export const CURRENCIES: Currency[] = [
  // Major currencies
  { code: 'USD', symbol: '$', name: 'US Dollar', region: 'Major' },
  { code: 'EUR', symbol: '€', name: 'Euro', region: 'Major' },
  { code: 'GBP', symbol: '£', name: 'British Pound', region: 'Major' },
  { code: 'JPY', symbol: '¥', name: 'Japanese Yen', region: 'Major' },
  { code: 'CNY', symbol: '¥', name: 'Chinese Yuan', region: 'Major' },
  { code: 'AUD', symbol: 'A$', name: 'Australian Dollar', region: 'Major' },
  { code: 'CAD', symbol: 'C$', name: 'Canadian Dollar', region: 'Major' },
  { code: 'CHF', symbol: 'CHF', name: 'Swiss Franc', region: 'Major' },
  
  // Middle East
  { code: 'AED', symbol: 'AED', name: 'UAE Dirham', region: 'Middle East' },
  { code: 'SAR', symbol: 'SAR', name: 'Saudi Riyal', region: 'Middle East' },
  { code: 'QAR', symbol: 'QAR', name: 'Qatari Riyal', region: 'Middle East' },
  { code: 'KWD', symbol: 'KWD', name: 'Kuwaiti Dinar', region: 'Middle East' },
  { code: 'BHD', symbol: 'BHD', name: 'Bahraini Dinar', region: 'Middle East' },
  { code: 'OMR', symbol: 'OMR', name: 'Omani Rial', region: 'Middle East' },
  { code: 'JOD', symbol: 'JOD', name: 'Jordanian Dinar', region: 'Middle East' },
  { code: 'ILS', symbol: '₪', name: 'Israeli New Shekel', region: 'Middle East' },
  { code: 'TRY', symbol: '₺', name: 'Turkish Lira', region: 'Middle East' },
  { code: 'IRR', symbol: 'IRR', name: 'Iranian Rial', region: 'Middle East' },
  { code: 'LBP', symbol: 'LBP', name: 'Lebanese Pound', region: 'Middle East' },
  { code: 'SYP', symbol: 'SYP', name: 'Syrian Pound', region: 'Middle East' },
  { code: 'YER', symbol: 'YER', name: 'Yemeni Rial', region: 'Middle East' },
  { code: 'IQD', symbol: 'IQD', name: 'Iraqi Dinar', region: 'Middle East' },
  
  // Africa
  { code: 'EGP', symbol: 'EGP', name: 'Egyptian Pound', region: 'Africa' },
  { code: 'NGN', symbol: '₦', name: 'Nigerian Naira', region: 'Africa' },
  { code: 'ZAR', symbol: 'R', name: 'South African Rand', region: 'Africa' },
  { code: 'KES', symbol: 'KSh', name: 'Kenyan Shilling', region: 'Africa' },
  { code: 'MAD', symbol: 'MAD', name: 'Moroccan Dirham', region: 'Africa' },
  { code: 'GHS', symbol: 'GH₵', name: 'Ghanaian Cedi', region: 'Africa' },
  { code: 'ETB', symbol: 'ETB', name: 'Ethiopian Birr', region: 'Africa' },
  { code: 'DZD', symbol: 'DZD', name: 'Algerian Dinar', region: 'Africa' },
  { code: 'XOF', symbol: 'CFA', name: 'West African CFA Franc', region: 'Africa' },
  { code: 'XAF', symbol: 'FCFA', name: 'Central African CFA Franc', region: 'Africa' },
  { code: 'TND', symbol: 'TND', name: 'Tunisian Dinar', region: 'Africa' },
  { code: 'SDG', symbol: 'SDG', name: 'Sudanese Pound', region: 'Africa' },
  { code: 'BWP', symbol: 'P', name: 'Botswana Pula', region: 'Africa' },
  { code: 'MZN', symbol: 'MT', name: 'Mozambican Metical', region: 'Africa' },
  { code: 'UGX', symbol: 'USh', name: 'Ugandan Shilling', region: 'Africa' },
  { code: 'RWF', symbol: 'RWF', name: 'Rwandan Franc', region: 'Africa' },
  { code: 'MWK', symbol: 'MK', name: 'Malawian Kwacha', region: 'Africa' },
  { code: 'LSL', symbol: 'LSL', name: 'Lesotho Loti', region: 'Africa' },
  { code: 'SZL', symbol: 'SZL', name: 'Swazi Lilangeni', region: 'Africa' },
  { code: 'MUR', symbol: '₨', name: 'Mauritian Rupee', region: 'Africa' },
  { code: 'SCR', symbol: '₨', name: 'Seychellois Rupee', region: 'Africa' },
  { code: 'CVE', symbol: 'CVE', name: 'Cape Verdean Escudo', region: 'Africa' },
  { code: 'GMD', symbol: 'GMD', name: 'Gambian Dalasi', region: 'Africa' },
  { code: 'SLL', symbol: 'Le', name: 'Sierra Leonean Leone', region: 'Africa' },
  { code: 'LRD', symbol: 'L$', name: 'Liberian Dollar', region: 'Africa' },
  { code: 'SOS', symbol: 'S', name: 'Somali Shilling', region: 'Africa' },
  { code: 'MGA', symbol: 'Ar', name: 'Malagasy Ariary', region: 'Africa' },
  { code: 'AOA', symbol: 'Kz', name: 'Angolan Kwanza', region: 'Africa' },
  { code: 'ZMW', symbol: 'ZK', name: 'Zambian Kwacha', region: 'Africa' },
  { code: 'BIF', symbol: 'BIF', name: 'Burundian Franc', region: 'Africa' },
  { code: 'DJF', symbol: 'DJF', name: 'Djiboutian Franc', region: 'Africa' },
  { code: 'GNF', symbol: 'FG', name: 'Guinean Franc', region: 'Africa' },
  { code: 'KMF', symbol: 'CF', name: 'Comorian Franc', region: 'Africa' },
  { code: 'STD', symbol: 'STD', name: 'São Tomé and Príncipe Dobra', region: 'Africa' },
  { code: 'MRU', symbol: 'MRU', name: 'Mauritanian Ouguiya', region: 'Africa' },
  
  // Asia
  { code: 'HKD', symbol: 'HK$', name: 'Hong Kong Dollar', region: 'Asia' },
  { code: 'MOP', symbol: 'MOP$', name: 'Macanese Pataca', region: 'Asia' },
  { code: 'KRW', symbol: '₩', name: 'South Korean Won', region: 'Asia' },
  { code: 'KPW', symbol: '₩', name: 'North Korean Won', region: 'Asia' },
  { code: 'THB', symbol: '฿', name: 'Thai Baht', region: 'Asia' },
  { code: 'SGD', symbol: 'S$', name: 'Singapore Dollar', region: 'Asia' },
  { code: 'MYR', symbol: 'RM', name: 'Malaysian Ringgit', region: 'Asia' },
  { code: 'IDR', symbol: 'Rp', name: 'Indonesian Rupiah', region: 'Asia' },
  { code: 'PHP', symbol: '₱', name: 'Philippine Peso', region: 'Asia' },
  { code: 'INR', symbol: '₹', name: 'Indian Rupee', region: 'Asia' },
  { code: 'VND', symbol: '₫', name: 'Vietnamese Dong', region: 'Asia' },
  { code: 'TWD', symbol: 'NT$', name: 'New Taiwan Dollar', region: 'Asia' },
  { code: 'PKR', symbol: '₨', name: 'Pakistani Rupee', region: 'Asia' },
  { code: 'BDT', symbol: '৳', name: 'Bangladeshi Taka', region: 'Asia' },
  { code: 'MMK', symbol: 'K', name: 'Burmese Kyat', region: 'Asia' },
  { code: 'KHR', symbol: '៛', name: 'Cambodian Riel', region: 'Asia' },
  { code: 'LAK', symbol: '₭', name: 'Lao Kip', region: 'Asia' },
  { code: 'LKR', symbol: 'Rs', name: 'Sri Lankan Rupee', region: 'Asia' },
  { code: 'NPR', symbol: '₨', name: 'Nepalese Rupee', region: 'Asia' },
  { code: 'MNT', symbol: '₮', name: 'Mongolian Tögrög', region: 'Asia' },
  { code: 'KZT', symbol: '₸', name: 'Kazakhstani Tenge', region: 'Asia' },
  { code: 'UZS', symbol: 'UZS', name: 'Uzbekistani Soʻm', region: 'Asia' },
  { code: 'TJS', symbol: 'TJS', name: 'Tajikistani Somoni', region: 'Asia' },
  { code: 'KGS', symbol: 'KGS', name: 'Kyrgyzstani Som', region: 'Asia' },
  { code: 'AZN', symbol: '₼', name: 'Azerbaijani Manat', region: 'Asia' },
  { code: 'GEL', symbol: '₾', name: 'Georgian Lari', region: 'Asia' },
  { code: 'AMD', symbol: '֏', name: 'Armenian Dram', region: 'Asia' },
  
  // Europe
  { code: 'SEK', symbol: 'kr', name: 'Swedish Krona', region: 'Europe' },
  { code: 'DKK', symbol: 'kr', name: 'Danish Krone', region: 'Europe' },
  { code: 'NOK', symbol: 'kr', name: 'Norwegian Krone', region: 'Europe' },
  { code: 'PLN', symbol: 'zł', name: 'Polish Zloty', region: 'Europe' },
  { code: 'CZK', symbol: 'Kč', name: 'Czech Koruna', region: 'Europe' },
  { code: 'HUF', symbol: 'Ft', name: 'Hungarian Forint', region: 'Europe' },
  { code: 'RUB', symbol: '₽', name: 'Russian Ruble', region: 'Europe' },
  { code: 'UAH', symbol: '₴', name: 'Ukrainian Hryvnia', region: 'Europe' },
  { code: 'RON', symbol: 'lei', name: 'Romanian Leu', region: 'Europe' },
  { code: 'BGN', symbol: 'лв', name: 'Bulgarian Lev', region: 'Europe' },
  { code: 'HRK', symbol: 'kn', name: 'Croatian Kuna', region: 'Europe' },
  { code: 'ISK', symbol: 'kr', name: 'Icelandic Krona', region: 'Europe' },
  { code: 'MKD', symbol: 'ден', name: 'Macedonian Denar', region: 'Europe' },
  { code: 'MDL', symbol: 'MDL', name: 'Moldovan Leu', region: 'Europe' },
  { code: 'RSD', symbol: 'дин', name: 'Serbian Dinar', region: 'Europe' },
  { code: 'ALL', symbol: 'L', name: 'Albanian Lek', region: 'Europe' },
  { code: 'BYN', symbol: 'Br', name: 'Belarusian Ruble', region: 'Europe' },
  { code: 'GIP', symbol: '£', name: 'Gibraltar Pound', region: 'Europe' },
  
  // North America
  { code: 'MXN', symbol: '$', name: 'Mexican Peso', region: 'North America' },
  { code: 'BSD', symbol: 'B$', name: 'Bahamian Dollar', region: 'North America' },
  { code: 'BBD', symbol: 'Bds$', name: 'Barbadian Dollar', region: 'North America' },
  { code: 'BZD', symbol: 'BZ$', name: 'Belize Dollar', region: 'North America' },
  { code: 'BMD', symbol: 'BD$', name: 'Bermudian Dollar', region: 'North America' },
  { code: 'KYD', symbol: 'CI$', name: 'Cayman Islands Dollar', region: 'North America' },
  { code: 'CRC', symbol: '₡', name: 'Costa Rican Colón', region: 'North America' },
  { code: 'CUP', symbol: '$MN', name: 'Cuban Peso', region: 'North America' },
  { code: 'DOP', symbol: 'RD$', name: 'Dominican Peso', region: 'North America' },
  { code: 'GTQ', symbol: 'Q', name: 'Guatemalan Quetzal', region: 'North America' },
  { code: 'HTG', symbol: 'G', name: 'Haitian Gourde', region: 'North America' },
  { code: 'HNL', symbol: 'L', name: 'Honduran Lempira', region: 'North America' },
  { code: 'JMD', symbol: 'J$', name: 'Jamaican Dollar', region: 'North America' },
  { code: 'NIO', symbol: 'C$', name: 'Nicaraguan Córdoba', region: 'North America' },
  { code: 'PAB', symbol: 'B/.', name: 'Panamanian Balboa', region: 'North America' },
  { code: 'TTD', symbol: 'TT$', name: 'Trinidad and Tobago Dollar', region: 'North America' },
  { code: 'XCD', symbol: 'EC$', name: 'East Caribbean Dollar', region: 'North America' },
  { code: 'ANG', symbol: 'ƒ', name: 'Netherlands Antillean Guilder', region: 'North America' },
  { code: 'SRD', symbol: '$', name: 'Surinamese Dollar', region: 'North America' },
  
  // South America
  { code: 'BRL', symbol: 'R$', name: 'Brazilian Real', region: 'South America' },
  { code: 'ARS', symbol: '$', name: 'Argentine Peso', region: 'South America' },
  { code: 'CLP', symbol: '$', name: 'Chilean Peso', region: 'South America' },
  { code: 'COP', symbol: '$', name: 'Colombian Peso', region: 'South America' },
  { code: 'PEN', symbol: 'S/', name: 'Peruvian Sol', region: 'South America' },
  { code: 'VES', symbol: 'Bs', name: 'Venezuelan Bolívar', region: 'South America' },
  { code: 'BOB', symbol: 'Bs', name: 'Bolivian Boliviano', region: 'South America' },
  { code: 'PYG', symbol: '₲', name: 'Paraguayan Guaraní', region: 'South America' },
  { code: 'UYU', symbol: '$U', name: 'Uruguayan Peso', region: 'South America' },
  { code: 'GYD', symbol: 'GY$', name: 'Guyanese Dollar', region: 'South America' },
  { code: 'ECS', symbol: 'ECS', name: 'Ecuadorian Sucre', region: 'South America' },
  
  // Oceania
  { code: 'NZD', symbol: 'NZ$', name: 'New Zealand Dollar', region: 'Oceania' },
  { code: 'FJD', symbol: 'FJ$', name: 'Fijian Dollar', region: 'Oceania' },
  { code: 'PGK', symbol: 'K', name: 'Papua New Guinean Kina', region: 'Oceania' },
  { code: 'SBD', symbol: 'SI$', name: 'Solomon Islands Dollar', region: 'Oceania' },
  { code: 'TOP', symbol: 'T$', name: 'Tongan Paʻanga', region: 'Oceania' },
  { code: 'VUV', symbol: 'VT', name: 'Vanuatu Vatu', region: 'Oceania' },
  { code: 'WST', symbol: 'WS$', name: 'Samoan Tala', region: 'Oceania' },
  { code: 'KID', symbol: '$', name: 'Kiribati Dollar', region: 'Oceania' },
  { code: 'MVR', symbol: 'MVR', name: 'Maldivian Rufiyaa', region: 'Oceania' },
  { code: 'XPF', symbol: 'CFP', name: 'CFP Franc', region: 'Oceania' },
  { code: 'TVD', symbol: 'TVD', name: 'Tuvaluan Dollar', region: 'Oceania' },
  { code: 'NAD', symbol: 'N$', name: 'Namibian Dollar', region: 'Oceania' },
];